### ISSUE TITLE
PHP parse error

### ISSUE THREAD

**Issue by agrimarcal** [Wngui/CS2WarcraftMod#11]
Got error 'PHP message: PHP Parse error:  syntax error, unexpected 'smartyRegisterFunction' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)

**Comment by agrimarcal** [comment]
Web Panel de control  bloqueada por este error

**Comment by agrimarcal** [comment]
No lo puedo solucionar

**Comment by Wngui** [comment]
This plugin does not provide any web panel functionality, the error message seems unrelated to CS2 Warcraft. Try disabling all your plugins and enable one by one to see where the issue is.
