### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by baskerdk** [Wngui/CS2WarcraftMod#2]
hi, I'm really happy for your courage and hope there will soon be more rasce and a shop maybe and vip ranke as unfortunately I'm not good at developing myself, it could be great I set up a server again and haven't run into any problems yet the one Danish sever who is on his way up

**Comment by Wngui** [comment]
Hey basker, thanks for the ideas you posted, I'll definitely take a look, but no promises. 
Good to hear about the new server in the motherland - I'm danish as well ;)

**Comment by baskerdk** [comment]
Dejligt og tak for dit hurtigt svar. Og rigtigt lækkert med dit mod har prøvet af finde noget line i lang tid. Så er glad for jeg fandt det igår

**Comment by baskerdk** [comment]
and maybe make it so you can get higher lvl than 16 maybe to 32
