### ISSUE TITLE
Link to more classe

### ISSUE THREAD

**Issue by baskerdk** [Wngui/CS2WarcraftMod#3]
https://github.com/awfulxaim/WCS-Races/tree/main/VG%20Main%20Characters

**Comment by Wngui** [comment]
Thanks basker for the inspiration, and interest in the project, lots of good ideas there!

**Comment by baskerdk** [comment]
yes thank you, you have to come up with ideas if you can't and just hope it will come to fruition and namely tried by turning up the maxlvl in WarcraftPlugin.cs but it didn't work

**Comment by Wngui** [comment]
You would have to increase both, max level & max skill level, it should work (i didn't test), but some of the classes would become wonky/extremely overpowered
MaxLevel = 31;
MaxSkillLevel = 10;

**Comment by baskerdk** [comment]
ok, I'll fix that. and see if it works

**Comment by baskerdk** [comment]
unfortunately it doesn't work. but otherwise thanks for the help ;D
