### ISSUE TITLE
Shapeshifter 

### ISSUE THREAD

**Issue by baskerdk** [Wngui/CS2WarcraftMod#4]
Shapeshifter cannot die after using its ultimate

**Comment by Wngui** [comment]
Hmm your right, seems like this was broken in a recent cs2 update. I'll take a look

**Comment by baskerdk** [comment]
thx

**Comment by Wngui** [comment]
Bug should be fixed now, with some minor improvements as well.

Please let me know if you get a chance to test it

**Comment by baskerdk** [comment]
yes i try

**Comment by baskerdk** [comment]
it works now Thanks for fixing it :D
