### ISSUE TITLE
Sound Volume Adjustment

### ISSUE THREAD

**Issue by gjonezin** [Wngui/CS2WarcraftMod#8]
Hi, thank you for this plugin. We've been waiting for something like this. Your work is appreciated.

As for this submission, I've been getting feedback from users that the sounds are too loud, and not aligned with the game volume settings. Is there any way for us to adjust the sound volume for this plugin only or can you update this plugin to align sound volume with game volume settings?

Thanks again.

**Comment by Wngui** [comment]
Hey gjonezin, thanks for the feedback. I'm guessing this is mostly related to the drone shooting sound? Otherwise let know. 
I've created a new release, where it instead uses the m4 silenced sound, let me know if it's better.

**Comment by gjonezin** [comment]
Thank you. It's actually the sound when you kill an enemy. But, the silencer will help.

**Comment by Wngui** [comment]
Got it. I guess you've set the bot difficulty above 4 and all the bots are named zombie? I recommend setting it to 4 or below as the necromancer might not work correctly, however I realize this is a little finicky, so I'll look into reworking it.

In the mean time I've removed the zombie killed sound

**Comment by gjonezin** [comment]
They are set to 3. But, yes the bots are named zombie as well. Only other sound that is loud or bothersome is the drone running into walls. I'm really just being picky here. Because, the mod is great.

I appreciate it.

**Comment by Wngui** [comment]
Regarding the drone bumping into walls sound, it's actually a hidden soccer ball which I use to manipulate the physics of the drone. 😅 It would require a bigger rewrite of the drone to remove it unfortunately, I'll think about it if I return to this logic, but for now closing this!
